@echo off
setlocal

set "REPO_ROOT=%~dp0.."
for %%I in ("%REPO_ROOT%") do set "REPO_ROOT=%%~fI"
set "CAA_WORKSPACE=%REPO_ROOT%\caa_workspace"
set "BRIDGE_RUNTIME=%CAA_WORKSPACE%\CatiaPyBridgeRuntime"
set "BRIDGE_BIN=%BRIDGE_RUNTIME%\code\bin"
set "BRIDGE_DICTIONARY=%BRIDGE_RUNTIME%\code\dictionary"
set "BRIDGE_PRODUCT_IC=%BRIDGE_RUNTIME%\code\productIC"
set "BRIDGE_MSGCATALOG=%BRIDGE_RUNTIME%\resources\msgcatalog"
set "INSTALL_CONFIG=%CAA_WORKSPACE%\Install_config_win_b64"
set "ENV_DIR=%CAA_WORKSPACE%\CATEnv"
set "ENV_NAME=CatiaPyBridge_B30"
set "ENV_FILE=%ENV_DIR%\%ENV_NAME%.txt"
set "LOCAL_USER_SETTING_FILE=%ENV_DIR%\%ENV_NAME%.user_settings.txt"

if not defined CATIA_BRIDGE_USER_SETTING_PATH (
  if exist "%LOCAL_USER_SETTING_FILE%" (
    set /p CATIA_BRIDGE_USER_SETTING_PATH=<"%LOCAL_USER_SETTING_FILE%"
  )
)

if not defined CATIA_BRIDGE_USER_SETTING_PATH (
  set "CATIA_BRIDGE_USER_SETTING_PATH=CSIDL_APPDATA\DassaultSystemes\CATSettings30"
)

if not defined CATIA_B30_INSTALL (
  if exist "%INSTALL_CONFIG%" (
    for /f "usebackq skip=1 delims=" %%I in ("%INSTALL_CONFIG%") do (
      if not defined CATIA_B30_INSTALL set "CATIA_B30_INSTALL=%%I"
    )
  )
)

if not defined CATIA_B30_INSTALL (
  echo CATIA_B30_INSTALL is not set and %INSTALL_CONFIG% was not usable.
  exit /b 1
)

set "CATSTART=%CATIA_B30_INSTALL%\win_b64\code\bin\CATSTART.exe"
if not exist "%CATSTART%" (
  echo CATSTART.exe not found: %CATSTART%
  exit /b 1
)

if not exist "%BRIDGE_DICTIONARY%\CatiaPyBridge.dico" (
  echo Isolated CatiaPyBridge dictionary not found: %BRIDGE_DICTIONARY%\CatiaPyBridge.dico
  exit /b 1
)

if not defined CATIA_MCP_PYTHON set "CATIA_MCP_PYTHON=python"
"%CATIA_MCP_PYTHON%" -m catia_mcp.caa.runtime_manifest --verify-runtime "%BRIDGE_RUNTIME%"
if errorlevel 1 exit /b 1

if not exist "%ENV_DIR%" mkdir "%ENV_DIR%"

(
  echo !----------------------------------------------------------
  echo !   DASSAULT SYSTEMES  -  V5 ENVIRONMENT FILE
  echo !----------------------------------------------------------
  echo ! MODE : User
  echo ! TYPE : CATIA_P3
  echo ! Generated by CatiaPyBridge start_catia_bridge_b30.bat
  echo !----------------------------------------------------------
  echo.
  echo CATInstallPath=%CATIA_B30_INSTALL%\win_b64
  echo CATDLLPath=%CATIA_B30_INSTALL%\win_b64\code\bin;%BRIDGE_BIN%
  echo CATICPath=%CATIA_B30_INSTALL%\win_b64\code\productIC;%BRIDGE_PRODUCT_IC%
  echo CATCommandPath=%CATIA_B30_INSTALL%\win_b64\code\command
  echo CATDictionaryPath=%CATIA_B30_INSTALL%\win_b64\code\dictionary;%BRIDGE_DICTIONARY%
  echo CATDocView=%CATIA_B30_INSTALL%\win_b64\doc
  echo CATReffilesPath=%CATIA_B30_INSTALL%\win_b64\reffiles
  echo CATFontPath=%CATIA_B30_INSTALL%\win_b64\resources\fonts
  echo CATGalaxyPath=%CATIA_B30_INSTALL%\win_b64\resources\galaxy
  echo CATGraphicPath=%CATIA_B30_INSTALL%\win_b64\resources\graphic;%CATIA_B30_INSTALL%\win_b64\resources\graphic\icons;%CATIA_B30_INSTALL%\win_b64\resources\graphic\figures;%CATIA_B30_INSTALL%\win_b64\resources\graphic\splashscreens;%CATIA_B30_INSTALL%\win_b64\resources\graphic\symbols;%CATIA_B30_INSTALL%\win_b64\resources\graphic\textures
  echo CATMsgCatalogPath=%CATIA_B30_INSTALL%\win_b64\resources\msgcatalog;%BRIDGE_MSGCATALOG%
  echo CATFeatureCatalogPath=%CATIA_B30_INSTALL%\win_b64\resources\featurecatalog
  echo CATDefaultCollectionStandard=%CATIA_B30_INSTALL%\win_b64\resources\standard
  echo CATKnowledgePath=%CATIA_B30_INSTALL%\win_b64\resources\knowledge
  echo CATStartupPath=%CATIA_B30_INSTALL%\win_b64\startup
  echo CATW3ResourcesPath=%CATIA_B30_INSTALL%\win_b64\docs
  echo CATReconcilePath=
  echo CATReferenceSettingPath=
  echo CATUserSettingPath=%CATIA_BRIDGE_USER_SETTING_PATH%
  echo CATCollectionStandard=
  echo CATTemp=CSIDL_LOCAL_APPDATA\DassaultSystemes\CATTemp
  echo CATMetasearchPath=DSKEY_TMPDIR
  echo CATW3PublishPath=DSKEY_TMPDIR
  echo CATSharedWorkbookPath=DSKEY_TMPDIR
  echo CATErrorLog=CSIDL_LOCAL_APPDATA\DassaultSystemes\CATTemp\error.log
  echo CATReport=CSIDL_LOCAL_APPDATA\DassaultSystemes\CATReport
  echo CATDisciplinePath=
  echo USER_HOME=CSIDL_PERSONAL
  echo JAVA_HOME=%%JAVA_HOME%%
  echo CLASSPATH_JDBC=
  echo CLASSPATH=%%CLASSPATH_JDBC%%;%%CLASSPATH%%
  echo PATH=%CATIA_B30_INSTALL%\win_b64\code\bin;%BRIDGE_BIN%;%CATIA_B30_INSTALL%\win_b64\code\command;%%JAVA_HOME%%\bin;%%PATH%%
) > "%ENV_FILE%"

echo Wrote CATIA environment: %ENV_FILE%
echo CATIA user settings: %CATIA_BRIDGE_USER_SETTING_PATH%

if /i "%~1"=="--prepare-only" (
  echo Prepared isolated CatiaPyBridge runtime: %BRIDGE_RUNTIME%
  exit /b 0
)

if "%~1"=="" (
  "%CATSTART%" -direnv "%ENV_DIR%" -env "%ENV_NAME%" -run CNEXT
) else (
  "%CATSTART%" -direnv "%ENV_DIR%" -env "%ENV_NAME%" %*
)

exit /b %errorlevel%
